### ISSUE TITLE
1장 코딩 중 겪는 혼란에 대한 이해 - 2장 신속한 코드 분석 

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Programmers-Brain#1]
1장 2장을 읽으며 들었던 생각이나 의문, 경험담  또는 참고거리 에 대해 간단히 정리해 봅시다~

**Comment by ynoolee** [comment]
1장, 2장은 LTM, STM 이 나와서 뇌과학 책을 읽는 것 같고 재밌었습니다 

지금까지 책을 읽으며 들었던 생각은 
- 역시 실무에서는 코드를 읽는 시간이 직접 쓰는 시간보다 많은 비중을 차지하는 것 같다. 코드를 빠르게 읽기 위해서는 코드를 머리속에 청크 단위로 잘 넣는 연습이 필요하겠다
  -  이를 위해서는 LTM 이 필요하니 , 내 지식이 중요하다. 잘 알고 있을 수록 '효율적으로 묶는 것이 가능' 하다. 
     - 예를들어 책에서 나온 '삽입 정렬' 예시 역시, 책에 나온 대로 실습해 보았을 때, 책의 코드를 기억하기 보다는 '삽입 정렬 + 오른차순, 변수명은 i,j 를 사용함 ' 이런식으로 알고 있던 LTM 에 추가적인 정보를 기억하는 식으로 함을 느꼈다.
     - 주니어 단계에서 책을 읽으며, 내용을 정리하는 일들에 너무 많은 시간이 든다고 생각했다. 반면 그렇게 하지 않을 경우 남는게 너무 없어서 고민이었는데, 지금은 내 LTM 을 남기는 게 중요하니 시간이 들어도 정리하는게 좋겠다는 생각을 하였다 
  - 개인적으로는 , 이래서 '유지보수하기 좋은 코드, 가독성 있는 코드' 가 중요한 것 같다는 생각도 드는 중 
    - '영상정보와 코드' 부분에서는 '코드스타일, 객체지향적 코드' 가 중요해 보인다고 생각되었음. 묶음으로 보이기에는 이 두가지가 중요하다고 생각되었기 때문
- '고수준(추상화 레벨이 높은) ' 의 주석문은 오히려 청킹하는데 도움이 될 수도 있다는 것이 와닿았음. 주석은 마냥 쓰면 안된다는 생각을 했는데, 추상적인 주석이라면 유지보수하기에도 아주 어렵지는 않을 것 같으며, 앞으로 나올 코드에 대해 예상해 보는데 도움도 될 듯.

**Comment by su-pernova** [comment]
`추상화`된 코드, `디자인 패턴`으로 짜여진 코드가 이해하기 쉽고 유지보수 하기 쉽다는 것은 익히 들어 알지만,
뇌 인지과학적인 이유에서 왜 이게 이해하기 쉽고 유지보수 하기 쉬운지를 풀어 설명해주니
추상화된 코드를 작성해야 하는 이유가 좀 더 와닿았고, 정말 내가 잘 추상화 했는지 돌아볼 수 있는 지표를 제공해 주는 듯 해 좋았습니다!

**Comment by YHLEE9753** [comment]
결국 경험에 따라 LTM 의 활용부분이 커지는 것이 고급 프로그래머와 초급 프로그래머를 나눠 주는거 같습니다. 추가로 청크로 코드를 분리하는 것도 인상깊었습니다. 해당 부분을 인지하고 코드를 작성하면 좀더 구조적으로 짤수 있을거 같습니다.

**Comment by HyoungUkJJang** [comment]
이번엔 준비가 미흡해서 2장을 아직 읽고 있는 중이지만,
1장을 천천히 읽었을 때 mian이라는 오탈자를 main으로 자연스럽게 인식하고 넘어가는 부분도 흥미로웠고 우리가 왜 코드를 읽을 때 혼란스러움을 겪는지 3가지 큰 맥락으로 설명해주는데 신기하고 재밌었습니다.

결국 자신이 어떤 상태인지를 잘 파악해야 문제 해결도 빠르게 해결할 수 있다 라는 느낌도 주는 것 같아서 좋았습니다.
