### ISSUE TITLE
8장 명명을 잘하는 방법

### ISSUE THREAD

**Issue by su-pernova** [Dev-Prison/Programmers-Brain#12]

**Comment by HyoungUkJJang** [comment]
이름을 짓는게 경험과 상관없이 계속해서 더 어렵다고 느껴지는 부분 중 하나인 것 같습니다 ㅠ

저희가 아무렇지 않게 사용하고 있던 명명 규칙에 관해 실제로 재밌는 연구결과를 통해 나온 것을 보며 신기하기도 하면서 개발자로서 이러한 고민을 많이 하지는 않았던 것 같아 찔리기도 했던 것 같습니다 ㅎㅎ

좋은 네이밍을 적용할 수 있는 좋은 꿀팁들이 많이 있었는데 이것 또한 회사에서 꼭 한번 적용해보고 싶네요 :) 내용 적으로는 크게 어려운 부분 없이 재밌게 읽었습니다 !

**Comment by YHLEE9753** [comment]
- 명명에서 중요한 것은 규칙이다
- 이름 틀로 단어 명칭의 양식을 정하고
- 프로젝트 어휘 사전으로 동의어를 통일하자
- 그리고 카멜케이스 짱짱맨
- 그리고 버틀러씨의 규칙 양식을 준수해라

**Comment by su-pernova** [comment]
코드리뷰 받을 때 의외로 코드 자체보다 메소드 / 변수명을 지적받았던 적이 많았는데요,
그만큼 함께 개발할 때 명명 규칙은 중요한 것 같습니다.

언어 마다 명명 규칙도 조금씩 달라지므로, 새로운 언어를 사용하게 된다면
그에 맞는 명명 규칙을 살펴보는 시간을 꼭 가져보는게 좋을 것 같습니다!
