### ISSUE TITLE
ch 9 나쁜코드와 인지 부하를 방지하는 두 가지 프레임워크 - ch 10: 복잡한 문제 해결을 더 잘하려면

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Programmers-Brain#15]
인상깊었던 내용!

**Comment by ynoolee** [comment]
답안지를 받은 그룹이 새로운 문제도 더 빠르게 풀었다는 예시가 뭔가 기억에 남네요 ㅋㅋ 확실히 알고리즘 1도 못할 때는 빨리 답지 보고 생각하고 빠르게 넘어가면서 더 많이 풀어보는게 더 낫긴 했던 기억이 나네요. 

컨벤션이나 추상적인 것도 너무 오래 잡고 있기 보다는 빨리 누군가로부터 답을 얻는게 더 나을 때도 많고요 

반면 개발 관련한 문제 해결 방식은 나름 혼자 오래 잡고 있는 것도 괜찮은 것 같다는 생각도 있긴 합니다. 왜 이걸 사용해야하지 이런거 고민하는거는 생각해야 기억에 오래 남긴 하는 거 같아요

**Comment by YHLEE9753** [comment]
22가지의 코드 스멜을 알아갈 수 있어 좋았습니다. 코드 스멜을 분석하여 행하지 않도록 안내하는 것도 좋았습니다.
10장은 많은 자기개발 영상에 있는 내용과 코드를 엮어서 설명하는 것이 흥미로웠습니다

**Comment by HyoungUkJJang** [comment]
클린 코드와 관련된 이야기와 유사하다는 느낌을 받아서 편하게 읽을 수 있었습니다. 무엇보다 22가지의 코드 스멜을 지키려면 코드를 작성할 때 생각을 많이 해야 할 것 같습니다 :)
