### ISSUE TITLE
ch11 코드를 작성하는 행위 - ch12 대규모 시스템의 설계와 개선

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Programmers-Brain#16]
느낀점~

**Comment by ynoolee** [comment]
멀티태스킹을 하면서 본인은 생상적이라고 착각하는 경향이 있다는 부분이 많이 찔렸네요.. 자율단계에 도달할 만큼 잘 하는 것도 아니니 당연히 자동화 되었을리가 없는데 말이죠 🤔

인지적 차원에서 '분산성' 관련 내용에서는 python 의 comprehension 을 예시로 들어줬는데요. 간단한 기능을 하는 것임에도 중간 산출물을 저장하는 변수들 하나 하나 다른 줄에 선언 하는 코드 작성으로 인해 더욱더 한눈에 들어오지 않던게 생각이 납니다. 문법을 알아두고 자동화 단계에 도달하면 간결한 코드가 더 이해하기 쉬운 코드가 되겠네요.

**Comment by su-pernova** [comment]
멀티태스킹 부분을 읽으면서 여러 도메인(예 : 예약, 결제를 동시에 개발하는 등)을 동시에 개발하는 것이
겉으로는 가능해 보여도, 막상 해보면 왜 어려운지 깨달을 수 있었습니다.
항상 이 부분을 유념하여 개발시 일정 수립 및 관리를 잘 해야 할 것 같아요...!

**Comment by YHLEE9753** [comment]
흥미로운 내용들입니다 프로그램언어를 인지적 관점으로 보는게 재밌네요
