### ISSUE TITLE
3장 프로그래밍 문법 빠르게 배우기 - 4장 복잡한 코드 읽는 방법

### ISSUE THREAD

**Issue by YHLEE9753** [Dev-Prison/Programmers-Brain#3]
ch 3 : 프로그래밍 문법 빠르게 배우기
ch 4 : 복잡한 코드 읽는 방법

**Comment by YHLEE9753** [comment]
3장 : 평생 공부해라
4장 : 코딩할 때 메모지에 잘 적으면서 디버깅하자

**Comment by su-pernova** [comment]
무작정 구글링 하기 전에 한번이라도 스스로 기억해내려 노력해본 적 있는가? 라는 묵직한 펀치...

**Comment by ynoolee** [comment]
요즘 뭔가를 많이 까먹어서, 일단 개념 복습하고 생각해야지~ 했는데 일단 스스로 생각해보려고 노력하는게 먼저였다... 일단 구글링 해서 쉽게 가려고 하지 말자..
