### ISSUE TITLE
5장 코드를 더 깊이 있게 이해하기 

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Programmers-Brain#7]
느낀점! 궁금한점!

**Comment by HyoungUkJJang** [comment]
5장의 내용은 전반적으로 실험 연구를 통한 이야기를 말해주는 부분이 많았던 것 같습니다.
개인적으로 개발자는 수학을 잘 해야 한다 라는 생각을 속으로 가지고 있었지만 동시에 정말일지 라는 생각을 함께 존재 했었지만 그에 대한 연구 결과를 보니 신기했습니다. 내용이 조금 어렵기도 했습니다.. ㅎㅎ

그래도 이미 작성된 코드를 더 잘이해하기 위해서 어떻게 하면 좋을지 지표를 많이 제공해주는 것 같아 좋았고 무엇보다 변수의 역할을 정할때 책에 있는 그림을 참고하여 적용해보면 좋을 것 같았고 꽤 재밌는 챕터였습니다 !

**Comment by ynoolee** [comment]
호출되는 메서드를 호출하는 측에 가까이 두는 것에 대해 단순히 '스크롤 내리는게 너무 귀찮아서' 라고 생각했었는데, '스크롤 내리는 사이에 발생하는 인지부하를 줄이기 위해서' 라고 말을 바꿔야 겠네요 
텍스트를 이해하는 전략을 가져오는 부분에서 '시각화' 가 제가 가장 많이 사용하는 방법인데요 
머리속에서 정리 되지 않을 때면 데이터 단위로라도 이 데이터가 앞으로 어떤 연산과 관련될지를 모두 나열해서 그루핑 하고는 합니다!

다른 분들은 코드를 이해하는 데 사용하는 자신만의 방법이 있으신지 궁금하네요 🤔

**Comment by YHLEE9753** [comment]
수학적 능력보다 언어 능력을 더 많이 사용되는 것이 매우 흥미로웠습니다. 수학잘하는 사람보다 국어 잘했던 사람이 코딩을 더 잘할려나..? 라는 생각도 들었네요. 추가로 순서대로 읽기보다 콜스택의 순서를 따라가는 것도 좋았습니다.

**Comment by su-pernova** [comment]
저번 장 부터 코드를 출력해서 끄적거려 보라는 이야기가 많이 나오네요!
이걸 편하게 해주는 시각화 도구를 인텔리제이 플러그인 등으로 만들어봐도(?) 재미있을 것 같습니다.
